"""Anthropic Contextual Retrieval augmentation.

For each chunk, a 1-3 sentence context paragraph is generated by Gemini 2.5 Flash
that locates the chunk within its parent document. The context is prepended to the
chunk text before embedding, improving retrieval recall on out-of-context fragments.

Reference: Anthropic "Contextual Retrieval" technique (2024).

Cache policy
------------
Generated context strings (NOT the full augmented text) are persisted to disk at
``{cache_dir}/{doc_id}.json`` as ``{chunk_id: context}`` mappings. A re-run for a
cached chunk_id skips the LLM call entirely, making large re-indexes free after the
first pass. The cache file is read on every call but only written when a new context
is generated. Corrupt or missing files are treated as empty and overwritten cleanly.
"""
from __future__ import annotations

import json
import os
from pathlib import Path

from app.llm.vertex_client import generate  # from-import kept at module level so tests can monkeypatch ctx.generate
from app.retrieval.chunker import Chunk
from app.settings import settings

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

DEFAULT_CACHE_DIR = Path(__file__).resolve().parents[2] / "data" / "contextual_cache"

_SYSTEM_PROMPT = (
    "You write 1-3 sentence context paragraphs that locate a chunk within its parent doc."
)

_USER_TEMPLATE = (
    "<document>{full_doc_text}</document>\n"
    "Here is the chunk we want to situate within the whole document:\n"
    "<chunk>{chunk_text}</chunk>\n"
    "Please give a short succinct context to situate this chunk for retrieval. "
    "Answer only with the context, nothing else."
)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _cache_path(doc_id: str, cache_dir: Path) -> Path:
    return cache_dir / f"{doc_id}.json"


def _read_cache(path: Path) -> dict[str, str]:
    """Return the cache dict for a doc, or {} on any read/parse error."""
    if not path.exists():
        return {}
    try:
        raw = path.read_text(encoding="utf-8")
        data = json.loads(raw)
        if isinstance(data, dict):
            return data
        return {}
    except Exception:
        return {}


def _write_cache(path: Path, data: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    os.replace(tmp, path)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def context_for(
    chunk: Chunk,
    full_doc_text: str,
    *,
    cache_dir: Path = DEFAULT_CACHE_DIR,
    model: str | None = None,
) -> str:
    """Return the 1-3 sentence context string for *chunk* within *full_doc_text*.

    Checks the on-disk cache first; calls Gemini Flash on a miss and writes the
    result back. The *context string only* (not the augmented text) is cached.
    """
    resolved_model = model if model is not None else settings.gemini_model_flash
    path = _cache_path(chunk.doc_id, cache_dir)
    cache = _read_cache(path)

    if chunk.chunk_id in cache:
        return cache[chunk.chunk_id]

    # Cache miss — call the LLM.
    user_text = _USER_TEMPLATE.format(
        full_doc_text=full_doc_text,
        chunk_text=chunk.text,
    )
    response = generate(
        resolved_model,
        user_text,
        system_instruction=_SYSTEM_PROMPT,
    )
    # response.text is Optional[str]: None on safety-blocked / thinking-only responses.
    context = (response.text or "").strip()

    if not context:
        # Transient block — do NOT cache so the chunk can be retried on the next run.
        return ""

    # Persist the new entry.
    cache[chunk.chunk_id] = context
    _write_cache(path, cache)

    return context


def contextualize(
    chunk: Chunk,
    full_doc_text: str,
    *,
    cache_dir: Path = DEFAULT_CACHE_DIR,
    model: str | None = None,
) -> str:
    """Return the chunk text prefixed with a Flash-generated context paragraph.

    Result format: ``f"{context}\\n\\n{chunk.text}"``.
    The context string is fetched via :func:`context_for` (cache-aware).
    """
    context = context_for(chunk, full_doc_text, cache_dir=cache_dir, model=model)
    if not context:
        return chunk.text
    return f"{context}\n\n{chunk.text}"
